# Generated by Django 5.2.1 on 2025-09-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История компании'),
        ),
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='about',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты компании'),
        ),
        migrations.AddField(
            model_name='about',
            name='sertificate',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификат компании'),
        ),
        migrations.AddField(
            model_name='about',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
