# Generated by Django 5.2.1 on 2025-09-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_about_history_about_logo_about_requisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video_link',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
    ]
