# Generated by Django 4.2.6 on 2025-05-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_userprofile_following'),
        ('properties', '0002_alter_category_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_percentage', models.PositiveIntegerField(verbose_name='Размер скидки (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Дата продажи')),
                ('contract_date', models.DateField(verbose_name='Дата договора')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено')], default='pending', max_length=10, verbose_name='Статус')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sales', to='accounts.userprofile', verbose_name='Агент')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sales', to='accounts.userprofile', verbose_name='Клиент')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.promo', verbose_name='Промокод')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
