# Generated by Django 4.2.6 on 2025-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_contract_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='contract_date',
            field=models.DateField(verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
    ]
