# Generated by Django 5.2.1 on 2025-05-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_staff_description'),
        ('sales', '0004_alter_sale_contract_date_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sales', to='accounts.userprofile', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_sales', to='accounts.userprofile', verbose_name='Клиент'),
        ),
    ]
