FROM python:3.11-slim

WORKDIR /app

COPY ../ .

RUN pip install -r requirements.txt

RUN python manage.py migrate

EXPOSE 8000 8001

CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:8000 & daphne -b 0.0.0.0 -p 8001 filtering_service.asgi:application"]