# Generated by Django 4.2.6 on 2025-05-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_promo_options_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
    ]
