# Generated by Django 5.2.1 on 2025-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_agent_alter_sale_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='contract_date',
            field=models.DateTimeField(verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата продажи'),
        ),
    ]
