# Generated by Django 5.2.1 on 2025-05-17 17:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +375 (29) XXX-XX-XX', regex='^\\+375\\s\\(?(17|25|29|33|44)\\)?\\s?\\d{3}-\\d{2}-\\d{2}$')])),
                ('birth_date', models.DateField()),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('agent', 'Сотрудник'), ('admin', 'Администратор')], default='client', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
