# Generated by Django 5.2.1 on 2025-05-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='accounts.userprofile', verbose_name='Подписки'),
        ),
    ]
