import inputs


def task2():
    """Function for calculation count of natural numbers in integer sequence
    """
    print("Program will calculate count of natural numbers in sequence")
    mode = inputs.valid_input("Enter mode type input of data:\n"
                              "0 - By keyboard.\n"
                              "1 - Auto generation.\n", int, 0, 1)
    count = 0
    if mode == 0:
        print("Enter integer numbers (end of input - 0):")
        while True:
            temp = inputs.valid_input("", int)
            if temp > 0:
                count += 1
            elif temp == 0:
                break
    else:
        auto_count = inputs.valid_input("Enter count of autogenerated "
                                        "numbers: ", int, 0)
        arr = []
        for _ in range(auto_count):
            temp = inputs.random_generator(int)
            arr.append(temp)
            if temp > 0:
                count += 1
        print(" ".join(map(str, arr)))

    print(f"Count of integer numbers = {count}")


if __name__ == "__main__":
    task2()
