# Generated by Django 5.2.1 on 2025-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='clients', to='accounts.userprofile', verbose_name='Клиенты'),
        ),
    ]
