# Generated by Django 4.2.6 on 2025-05-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='description',
        ),
    ]
